#!/usr/bin/env bash

set -e

cd "$( dirname "${BASH_SOURCE[0]}" )/.."

if [ -f /usr/libexec/java_home ]; then
    export JAVA_HOME="`/usr/libexec/java_home -v '1.7'`"
fi

./gradlew :examples:classes

./gradlew :contractorj:run --debug-jvm -Dexec.args="--classpath ../examples/build/classes/main --class \"$1\" --dot \"$1.dot\" \"${@:2}\""

dot "$1.dot" -T png -o "$1.png"

