#!/usr/bin/env bash

set -e

cd "$( dirname "${BASH_SOURCE[0]}" )/.."

./gradlew :examples:classes
./gradlew :contractorj:installDist

contractorj/build/install/contractorj/bin/contractorj --classpath examples/build/classes/main --corral /Users/pato/facultad/tesis/tools/corral/bin/Debug/corral.exe --class "$1" --dot "$1.dot" --xml "$1.xml" "${@:2}"

dot "$1.dot" -T png -o "$1.png"

